---
abstract: 'Send messages'
author:
  - 'Nic Sandfield <niczero@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.3'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142690'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojar-Message
no_index:
  directory:
    - t
    - inc
    - data
    - test
requires:
  MIME::Entity: '5.5'
  Mojar: '2'
  Mojar::Cron: '0.2'
  Mojolicious: '5'
  perl: '5.010001'
resources:
  bugtracker: http://github.com/niczero/mojar-message/issues
  homepage: http://niczero.github.com/mojar
  license: http://www.opensource.org/licenses/artistic-license-2.0
  repository: http://github.com/niczero/mojar-message
version: 1.053
